#!/usr/bin/env python

import sys

from ros_industrial_dashboard.dashboard import Dashboard
from rqt_gui.main import Main

plugin = 'ros_industrial_dashboard.dashboard.Dashboard'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=Dashboard.add_arguments))
